version: "3.3"

services:

  # System Manager REST API of Root Orchestrator
  system_manager:
    build: ./../root_orchestrator/system-manager-python/. 
    hostname: system_manager
    container_name: system_manager
    network_mode: "host" 
    depends_on:
      - mongo_root
      - cloud_scheduler
      - root_service_manager
    environment:
      - CLOUD_MONGO_URL=localhost
      - CLOUD_MONGO_PORT=10007
      - CLOUD_SCHEDULER_URL=localhost
      - CLOUD_SCHEDULER_PORT=10004
      - NET_PLUGIN_URL=localhost
      - NET_PLUGIN_PORT=10099


  # MongoDB in Root Orchestrator
  mongo_root:
    image: mongo:3.6
    container_name: mongo
    hostname: mongo
    network_mode: "host"
    volumes:
      - 'mongodb_data:/mongodb'
    command: mongod --port 10007

  # Root-level mongoDB
  mongo_rootnet:
    image: mongo:3.6
    container_name: mongo_net
    hostname: mongo_net
    network_mode: "host"
    volumes:
      - 'mongodb_net_data:/mongodb'
    command: mongod --port 10008


  # Service Manager
  root_service_manager:
    image: ghcr.io/oakestra/oakestra-net/root-service-manager:latest
    container_name: root_service_manager
    hostname: root_service_manager
    network_mode: "host"
    environment:
      - MY_PORT=10099
      - SYSTEM_MANAGER_URL=localhost
      - SYSTEM_MANAGER_PORT=10000
      - CLOUD_MONGO_URL=localhost
      - CLOUD_MONGO_PORT=10008
    depends_on:
      - mongo_rootnet


  # Redis for the Cloud Scheduler
  redis:
    image: redis
    hostname: redis
    container_name: redis
    network_mode: "host"
    command: redis-server --requirepass cloudRedis


  grafana:
    image: grafana/grafana
    hostname: grafana
    container_name: grafana
    network_mode: "host"


  # Cloud Scheduler
  cloud_scheduler:
    image: ghcr.io/oakestra/oakestra/cloud-scheduler:latest
    container_name: cloud_scheduler
    hostname: cloud_scheduler
    network_mode: "host"
    environment:
      - MY_PORT=10004
      - SYSTEM_MANAGER_URL=localhost
      - SYSTEM_MANAGER_PORT=10000
      - CLOUD_MONGO_URL=localhost
      - CLOUD_MONGO_PORT=10007
      - REDIS_ADDR=redis://:cloudRedis@localhost:6379
    depends_on:
      - redis
      - mongo_root

  # MQTT
  mqtt:
    image: eclipse-mosquitto:1.6
    hostname: mqtt
    container_name: mqtt
    network_mode: "host"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /mosquitto/data
      - /mosquitto/log
    healthcheck:
      test: [ "CMD-SHELL", "timeout -t 5 mosquitto_sub -t '$$SYS/#' -C 1 | grep -v Error || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 6

volumes:
  mongodb_data:
    driver: local
  mongodb_net_data:
    driver: local
